### PR TITLE
run: add Procfile to run on toolforge

### PR DESCRIPTION
**Pull request by david-caro**
This allows running on the newer toolforge platform using:
```
toolforge jobs run \
    --schedule '0 19 */2 * *' \
    --command run-cron \
    --image tool-erex-yomi/tool-erex-yomi:latest \
    --filelog
```

### CODE REVIEW

**Review by abartov — APPROVED** [review]

**Comment by abartov** [comment]
Thank you very much!

**Comment by abartov** [comment]
@david-caro:

Made time to attempt to implement this on toolforge, but:

1. after the build command, the run command line offered does not work (--filelog is ambiguous, and further requires a parameter; the `name` parameter is mandatory). 
2. The scheduled job seems to have run (```toolforge jobs show erex-yomi``` shows "last schedule time"), but no log was created in the directory and the email (the tool sends a daily email digest) was not sent. So some error must have happened, but how do I see which? (```toolforge jobs logs erex-yomi``` says the job does not have any logs available.

**Comment by david-caro** [comment]
> @david-caro:
> 
> Made time to attempt to implement this on toolforge, but:
> 
>     1. after the build command, the run command line offered does not work (--filelog is ambiguous, and further requires a parameter; the `name` parameter is mandatory).
> 

Yep sorry, that feature was rolled back as it was not working as expected (will be merged with https://phabricator.wikimedia.org/T353537, but might take some  time).

The command would be (I think you were able to guess it):
```
toolforge jobs run \
    --schedule '0 19 */2 * *' \
    --command run-cron \
    --image tool-erex-yomi/tool-erex-yomi:latest \
    <job-name>
```

>     2. The scheduled job seems to have run (`toolforge jobs show erex-yomi` shows "last schedule time"), but no log was created in the directory and the email (the tool sends a daily email digest) was not sent. So some error must have happened, but how do I see which? (`toolforge jobs logs erex-yomi` says the job does not have any logs available.

Yep, buildservice jobs don't create logs in the home directory by themselves (yet! that's the task I linked earlier).

`toolforge jobs logs erex-yoml` should have shown the logs of the last run :/, I'll give it a look

**Comment by david-caro** [comment]
Opened #19 with a fix (please try)

**Pull request merged**
